'use client'

import { useState } from 'react'
import { createClient } from '@/utils/supabase/client'
import { showSuccessToast, showErrorToast } from '@/utils/toast'
import { useLang } from '@/components/lang-provider'
import { User, Phone, ShieldCheck, Mail, Save, Plus, X, Loader2, Users } from 'lucide-react'

export default function ProfileClient({ currentUser, currentProfile, allProfiles }: { currentUser: any, currentProfile: any, allProfiles: any[] }) {
    const supabase = createClient()
    const { t } = useLang()

    // My Profile State
    const [profileData, setProfileData] = useState({
        full_name: currentProfile?.full_name || '',
        phone: currentProfile?.phone || '',
        sports_role: currentProfile?.sports_role || 'Entrenador'
    })
    const [isSavingMyProfile, setIsSavingMyProfile] = useState(false)

    // Staff Management State
    const [staff, setStaff] = useState(allProfiles)
    const [isCreatingStaff, setIsCreatingStaff] = useState(false)
    const [newStaff, setNewStaff] = useState({ full_name: '', sports_role: 'Entrenador', phone: '' })
    const [isSavingStaff, setIsSavingStaff] = useState(false)

    // Roles permitidos por el Check Constraint de la DB
    const roles = ['Head Coach', 'Entrenador', 'Preparador Físico', 'Manager']

    // Admin check
    const isAdmin = currentProfile?.sports_role === 'Head Coach'

    const handleUpdateMyProfile = async (e: React.FormEvent) => {
        e.preventDefault()
        setIsSavingMyProfile(true)

        const { error } = await supabase.from('profiles').update(profileData).eq('id', currentUser.id)

        if (!error) {
            showSuccessToast(t.profilePage.successProfile, t.profilePage.successProfileDesc)
        } else {
            console.error(error)
            showErrorToast(t.profilePage.errorTitle, 'No se pudieron actualizar tus datos.')
        }
        setIsSavingMyProfile(false)
    }

    const handleCreateFakeStaff = async (e: React.FormEvent) => {
        e.preventDefault()
        setIsSavingStaff(true)

        // Insert using default random uuid generated by Supabase (if FK allows)
        const { data, error } = await supabase.from('profiles').insert([newStaff]).select()

        if (!error && data) {
            setStaff([data[0], ...staff])
            setIsCreatingStaff(false)
            setNewStaff({ full_name: '', sports_role: 'Entrenador', phone: '' })
            showSuccessToast(t.profilePage.successStaff, t.profilePage.successStaffDesc)
        } else {
            console.error('Insert constraint error:', error, JSON.stringify(error))
            // Error code 23503 is foreign_key_violation
            if (error?.code === '23503' || error?.code === '42501') {
                showErrorToast(t.profilePage.securityError, t.profilePage.securityErrorDesc)
            } else {
                showErrorToast(t.profilePage.errorTitle, 'No se pudo crear. ' + (error?.message || 'Revisar RLS'))
            }
        }
        setIsSavingStaff(false)
    }

    return (
        <div className="p-6 md:p-10 min-h-full bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-liceo-primary/30 via-background to-background dark:from-liceo-primary/20 dark:via-background dark:to-background text-foreground transition-colors space-y-8 max-w-7xl mx-auto">

            <header className="mb-8">
                <h1 className="text-4xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-liceo-primary to-liceo-accent dark:from-white dark:to-liceo-accent mb-2">
                    {t.profilePage.title}
                </h1>
                <p className="text-gray-500 dark:text-gray-400 font-medium tracking-wide">
                    {t.profilePage.subtitle}
                </p>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">

                {/* MY PROFILE */}
                <div className="bg-white dark:bg-[#0B1526] rounded-3xl p-6 md:p-8 shadow-xl border border-gray-200 dark:border-white/10 flex flex-col h-full">
                    <h2 className="text-2xl font-black mb-6 flex items-center gap-3 dark:text-white">
                        <User className="w-6 h-6 text-liceo-primary dark:text-[#5EE5F8]" />
                        {t.profilePage.myPersonalData}
                    </h2>

                    <div className="flex items-center gap-4 mb-8 bg-gray-50 dark:bg-black/20 p-4 rounded-2xl border border-gray-100 dark:border-white/5">
                        <div className="w-16 h-16 bg-liceo-primary text-white dark:bg-[#5EE5F8] dark:text-[#061B30] rounded-full flex items-center justify-center font-black text-2xl uppercase shadow-md">
                            {profileData.full_name ? profileData.full_name.charAt(0) : currentUser.email?.charAt(0)}
                        </div>
                        <div>
                            <p className="text-sm text-gray-500 font-bold uppercase tracking-wider flex items-center gap-1.5"><Mail className="w-3.5 h-3.5" /> {t.profilePage.accessEmail}</p>
                            <p className="font-bold text-gray-900 dark:text-white">{currentUser.email}</p>
                        </div>
                    </div>

                    <form onSubmit={handleUpdateMyProfile} className="space-y-5 flex-1 flex flex-col">
                        <div>
                            <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 ml-1">{t.profilePage.fullName}</label>
                            <div className="relative">
                                <User className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                                <input
                                    required
                                    value={profileData.full_name}
                                    onChange={e => setProfileData({ ...profileData, full_name: e.target.value })}
                                    className="w-full mt-1 pl-12 pr-4 py-3.5 rounded-xl border border-gray-200 dark:border-white/10 bg-white dark:bg-white/5 focus:outline-none focus:ring-2 focus:ring-liceo-primary font-bold dark:text-white transition-all"
                                    placeholder="Ej: Mario Gómez"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 ml-1">{t.profilePage.phoneMsg}</label>
                            <div className="relative">
                                <Phone className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                                <input
                                    value={profileData.phone}
                                    onChange={e => setProfileData({ ...profileData, phone: e.target.value })}
                                    className="w-full mt-1 pl-12 pr-4 py-3.5 rounded-xl border border-gray-200 dark:border-white/10 bg-white dark:bg-white/5 focus:outline-none focus:ring-2 focus:ring-liceo-primary font-bold dark:text-white transition-all"
                                    placeholder="+54 9 11 1234 5678"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 ml-1">{t.profilePage.role}</label>
                            <div className="relative">
                                <ShieldCheck className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                                <select
                                    value={profileData.sports_role}
                                    onChange={e => setProfileData({ ...profileData, sports_role: e.target.value })}
                                    className="w-full mt-1 pl-12 pr-4 py-3.5 rounded-xl border border-gray-200 dark:border-white/10 bg-white dark:bg-white/5 focus:outline-none focus:ring-2 focus:ring-liceo-primary font-bold dark:text-white transition-all appearance-none"
                                >
                                    {roles.map(r => <option key={r} value={r}>{r}</option>)}
                                </select>
                            </div>
                        </div>

                        <div className="mt-auto pt-8">
                            <button type="submit" disabled={isSavingMyProfile} className="w-full py-3.5 rounded-xl font-bold bg-liceo-primary hover:bg-liceo-primary/90 text-white dark:bg-[#5EE5F8] dark:hover:bg-[#4bc8da] dark:text-[#061B30] flex items-center justify-center gap-2 transition-all shadow-lg hover:shadow-xl disabled:opacity-50">
                                {isSavingMyProfile ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />}
                                {t.profilePage.saveMyData}
                            </button>
                        </div>
                    </form>
                </div>

                {/* STAFF MANAGEMENT */}
                <div className="bg-white/80 dark:bg-[#0B1526]/80 backdrop-blur-xl rounded-3xl p-6 md:p-8 shadow-xl border border-gray-200 dark:border-white/10 flex flex-col h-full relative">
                    <div className="flex justify-between items-center mb-6">
                        <h2 className="text-2xl font-black flex items-center gap-3 dark:text-white">
                            <Users className="w-6 h-6 text-liceo-accent dark:text-[#5EE5F8]" />
                            {t.profilePage.staffDir}
                        </h2>
                        {isAdmin && (
                            <button onClick={() => setIsCreatingStaff(true)} className="bg-gray-100 hover:bg-gray-200 dark:bg-white/10 dark:hover:bg-white/20 p-2.5 rounded-xl transition-colors">
                                <Plus className="w-5 h-5 text-gray-700 dark:text-white" />
                            </button>
                        )}
                    </div>

                    {isAdmin ? (
                        <div className="bg-orange-50 dark:bg-orange-500/10 border border-orange-200 dark:border-orange-500/20 rounded-2xl p-4 mb-6 text-xs text-orange-800 dark:text-orange-300 font-medium">
                            <strong className="block mb-1">{t.profilePage.adminMode}</strong>
                            {t.profilePage.adminModeMsg}
                        </div>
                    ) : (
                        <p className="text-xs text-gray-500 dark:text-gray-400 font-medium mb-6">
                            {t.profilePage.staffListMsg}
                        </p>
                    )}

                    <div className="flex-1 overflow-y-auto space-y-3 pr-2 border-t border-gray-100 dark:border-white/5 pt-4">
                        {staff.map(member => (
                            <div key={member.id} className="bg-white dark:bg-[#102035] p-4 rounded-2xl border border-gray-100 dark:border-white/5 flex items-center gap-4 shadow-sm group">
                                <div className="w-10 h-10 bg-gray-100 dark:bg-white/5 rounded-full flex items-center justify-center font-black text-gray-500 dark:text-gray-300">
                                    {member.full_name ? member.full_name.charAt(0) : 'U'}
                                </div>
                                <div className="flex-1">
                                    <h3 className="font-bold text-gray-900 dark:text-white text-sm">{member.full_name || 'Sin Nombre Acordado'}</h3>
                                    <p className="text-[10px] text-liceo-primary dark:text-[#5EE5F8] font-black uppercase tracking-widest">{member.sports_role}</p>
                                </div>
                                {member.id === currentUser.id && (
                                    <span className="text-[9px] bg-emerald-100 text-emerald-600 dark:bg-emerald-500/20 dark:text-emerald-400 font-bold px-2 py-0.5 rounded uppercase tracking-widest">
                                        {t.profilePage.youTag}
                                    </span>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* CREATE FAKE STAFF MODAL */}
            {isCreatingStaff && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                    <div className="bg-white dark:bg-[#0B1526] w-full max-w-sm rounded-3xl p-6 shadow-2xl border border-gray-200 dark:border-white/10 animate-in fade-in zoom-in-95">
                        <div className="flex justify-between items-center mb-6">
                            <h2 className="text-xl font-black dark:text-white">{t.profilePage.addTestStaff}</h2>
                            <button onClick={() => setIsCreatingStaff(false)} className="p-2 bg-gray-100 hover:bg-gray-200 dark:bg-white/5 dark:hover:bg-white/10 rounded-full"><X className="w-4 h-4 dark:text-white" /></button>
                        </div>
                        <form onSubmit={handleCreateFakeStaff} className="space-y-4">
                            <div>
                                <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{t.profilePage.fullName}</label>
                                <input required value={newStaff.full_name} onChange={e => setNewStaff({ ...newStaff, full_name: e.target.value })} className="w-full mt-1 px-4 py-3 rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-white/5 focus:outline-none focus:ring-2 focus:ring-liceo-primary font-bold dark:text-white" />
                            </div>
                            <div>
                                <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{t.profilePage.role}</label>
                                <select value={newStaff.sports_role} onChange={e => setNewStaff({ ...newStaff, sports_role: e.target.value })} className="w-full mt-1 px-4 py-3 rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-white/5 focus:outline-none focus:ring-2 focus:ring-liceo-primary font-bold dark:text-white appearance-none">
                                    {roles.map(r => <option key={r} value={r}>{r}</option>)}
                                </select>
                            </div>
                            <button type="submit" disabled={isSavingStaff} className="w-full mt-6 py-3 rounded-xl font-bold bg-liceo-primary text-white dark:bg-[#5EE5F8] dark:text-[#061B30] hover:opacity-90 flex justify-center items-center gap-2">
                                {isSavingStaff ? <Loader2 className="w-5 h-5 animate-spin" /> : t.profilePage.addWithoutAuth}
                            </button>
                        </form>
                    </div>
                </div>
            )}
        </div>
    )
}
